name: build project

on:
  push:
    tags:
    - '*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Get Version
      run: echo TAG_NAME=${GITHUB_REF/refs\/tags\//} >> $GITHUB_ENV
      
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: myci-actions/add-deb-repo@11
      with:
        repo: deb http://archive.ubuntu.com/ubuntu focal main universe
        repo-name: focal
        
    - name: Install Deps
      run: |
        sudo apt-get install -y libevent-dev libcurl4-openssl-dev g++-8
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  run: ctest -C ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: release_${{env.TAG_NAME}}
        path: ${{github.workspace}}/build/out/

